### ISSUE TITLE
https://rollbar.com/nextdoor/nextdoor/items/237418/

### ISSUE THREAD

**Issue by drewgbarnes** [Nextdoor/ndkale#21]
We get a ton of these rollbars. Can we get rid of them?

would this just work?:

`if message in self._incomplete_messages:`

  `self._incomplete_messages.remove(message)`

**Comment by mrterry** [comment]
Maybe.  The deeper problem looks like `_run_batch` and `_release_batch` are being executed concurrently.  `_run_batch()` sets `self._incomplete_messages`, then `_release_batch()` replaces it with empty list.  💣 💥 

Shared mutable state sucks.

**Comment by swaggy** [comment]
Fixed in #22
