### ISSUE TITLE
 YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe

### ISSUE THREAD

**Issue by caputomarcos** [Nextdoor/ndkale#39]
Hi folks,

 I've the following error when running taskwork.

python3.7/site-packages/kale/queue_info.py:192: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  queues_from_config = yaml.load(fp)

kind regards,

MCaputo.

fixed:
[commit](https://github.com/caputomarcos/ndkale/commit/2054c110aacb3486e58f09a22a2338ceb7f6825b)

**Comment by RKTMN** [comment]
Looks like we addressed that here: https://github.com/Nextdoor/ndkale/pull/40
